baseurl = "https://jimmysong.io/"
DefaultContentLanguage = "zh"
hasCJKLanguage = true
languageCode = "zh"
title = "Jimmy Song"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = false
pygmentCodeFences = true
googleAnalytics = "UA-93485976-1"
defaultContentLanguageInSubdir= false

[languages]
  [languages.zh]
    languageName = "中文"
    weight = 1
    contentDir = "content/zh"
  [languages.en]
    languageName = "English"
    weight = 2
    contentDir = "content/en"

[Params]
hello = "Hi,I'm Jimmy"
subtitle = "A CNCF Ambassador and Developer Advocate on Cloud Native"
logo = "https://res.cloudinary.com/jimmysong/raw/upload/rootsongjc-hugo/avatar-icon.png"
favicon = "https://res.cloudinary.com/jimmysong/raw/upload/rootsongjc-hugo/favicon.ico"
share_img = "/img/jimmysong.jpg"
commit = false
rss = true
# ad section, comment this to disable it
#ad = true
# GoogleAdsense
#adsense = true
# reward button, comment this to disable it
reward = true
# baguettebox gallery, comment this to disable it
baguettebox = true
baiduKey = "11f7d254cfa4e0ca44b175c66d379ecc"
#comments = false
#sharebutton = true
algolia = "d2134c5a8d250e6d3246594240c45201" # API key
#gcse = "012737790962522169780:fd1izxsfgrs" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
description = "宋净超的博客|Cloud Native|云原生布道师"
errorpage = "https://res.cloudinary.com/jimmysong/image/upload/images/404-not-found-cat.png"
about_me = """关注Kubernetes/Service Mesh/Serverless/Cloud Native/Open Source，关注微信公众号获取最新资讯。![ServiceMesher公众号二维码](/img/servicemesher-wechat-public-account-tiny.jpg)"""
recent_posts = true
contact_me = """请扫描下面的微信二维码联系我加入微信交流群，请备注姓名-公司，否则可能不予通过![Jimmy Song的微信](/img/jimmy-song-wechat-tiny.jpg)"""

[[Params.bigimg]]
src = "https://gw.alipayobjects.com/mdn/rms_91f3e6/afts/img/A*cr5NRICPMPwAAAAAAAAAAABkARQnAQ"
desc = "SOFAStack Cloud Native Workshop at KubeCon China 2019 Shanghai - Jun 24, 2019"

[[Params.bigimg]]
src = "https://gw.alipayobjects.com/mdn/rms_91f3e6/afts/img/A*ClY-RacU9u4AAAAAAAAAAABkARQnAQ"
desc = "ServiceMesher at KubeCon China 2019 Shanghai - Jun 25, 2019"

[Author]
  name = "Jimmy Song(宋净超)"
  website = "https://jimmysong.io/about"
  #email = "jimmysong@jimmysong.io"
  facebook = "jimmysongio"
  #googleplus = "+jimmysong" # or xxxxxxxxxxxxxxxxxxxxx
  github = "rootsongjc"
  twitter = "jimmysongio"
  linkedin = "jimmysongio"
  #500px = "jimmysongio"
  #medium = "jimmysongio"
  #instagram = "jimmysongio"
  weibo = "jimmysongio"

[[menu.main]]
    identifier = "Categories"
    name = "文章分类"
    weight = 1

[[menu.main]]
    parent = "Categories"
    name = "kubernetes"
    url = "categories/kubernetes"
    weight = 1

[[menu.main]]
    parent = "Categories"
    name = "Istio"
    url = "categories/istio"
    weight = 2

[[menu.main]]
    parent = "Categories"
    name = "Cloud Native"
    url = "categories/cloud-native"
    weight = 3

[[menu.main]]
    parent = "Categories"
    name = "Open Source"
    url = "categories/open-source"
    weight = 4

[[menu.main]]
    parent = "Categories"
    name = "Service Mesh"
    url = "categories/service-mesh"
    weight = 5

[[menu.main]]
    parent = "Categories"
    name = "Devops"
    url = "categories/devops"
    weight = 6

[[menu.main]]
    parent = "Categories"
    name = "Serverless"
    url = "categories/serverless"
    weight = 7

[[menu.main]]
    parent = "Categories"
    name = "Tags"
    url = "tags"
    weight = 8

[[menu.main]]
    identifier = "Gitbooks"
    name = "电子书"
    weight = 2

[[menu.main]]
    parent = "Gitbooks"
    name = "Istio handbook"
    url = "istio-handbook"
    weight = 1

[[menu.main]]
    parent = "Gitbooks"
    name = "Kubernetes handbook"
    url = "kubernetes-handbook"
    weight = 2

[[menu.main]]
    parent = "Gitbooks"
    name = "Serverless handbook"
    url = "serverless-handbook"
    weight = 3

[[menu.main]]
    parent = "Gitbooks"
    name = "Docker handbook"
    url = "docker-handbook"
    weight = 4

[[menu.main]]
    parent = "Gitbooks"
    name = "Hugo Handbook"
    url = "hugo-handbook"
    weight = 5

[[menu.main]]
    parent = "Gitbooks"
    name = "谷歌工程实践"
    url = "eng-practices"
    weight = 6

[[menu.main]]
    parent = "Gitbooks"
    name = "迁移到云原生应用架构"
    url = "migrating-to-cloud-native-application-architectures"
    weight = 7

[[menu.main]]
    identifier = "Books"
    name = "出版物"
    weight = 3

[[menu.main]]
    parent = "Books"
    name = "未来架构 - 从服务化到云原生"
    url = "posts/future-architecture-from-soa-to-cloud-native"
    weight = 1

[[menu.main]]
    parent = "Books"
    name = "Cloud Native Go"
    url = "posts/cloud-native-go"
    weight = 2

[[menu.main]]
    parent = "Books"
    name = "Cloud Native Python"
    url = "posts/cloud-native-python"
    weight = 3

[[menu.main]]
    parent = "Books"
    name = "Cloud Native Java"
    url = "posts/cloud-native-java"
    weight = 4

[[menu.main]]
    name = "招聘"
    identifier = "jobs"
    url = "jobs"
    weight = 4

[[menu.main]]
    name = "关于"
    url = "about"
    weight = 5

[[languages.en.menu.main]]
    identifier = "Blog"
    name = "Blog"
    url = "/posts/"
    weight = 1

[[languages.en.menu.main]]
    identifier = "Gitbooks"
    name = "Gitbooks"
    weight = 2

[[languages.en.menu.main]]
    parent = "Gitbooks"
    name = "Istio handbook"
    url = "istio-handbook"
    weight = 1

[[languages.en.menu.main]]
    parent = "Gitbooks"
    name = "Kubernetes handbook"
    url = "kubernetes-handbook"
    weight = 2

[[languages.en.menu.main]]
    parent = "Gitbooks"
    name = "Docker handbook"
    url = "docker-handbook"
    weight = 3

[[languages.en.menu.main]]
    parent = "Gitbooks"
    name = "Hugo Handbook"
    url = "hugo-handbook"
    weight = 4

[[languages.en.menu.main]]
    parent = "Gitbooks"
    name = "Migrating to Cloud Native"
    url = "migrating-to-cloud-native-application-architectures"
    weight = 5

[[languages.en.menu.main]]
    identifier = "Books"
    name = "Books"
    weight = 3

[[languages.en.menu.main]]
    parent = "Books"
    name = "Future Architecture"
    url = "posts/future-architecture-from-soa-to-cloud-native"
    weight = 1

[[languages.en.menu.main]]
    parent = "Books"
    name = "Cloud Native Go"
    url = "posts/cloud-native-go"
    weight = 2

[[languages.en.menu.main]]
    parent = "Books"
    name = "Cloud Native Python"
    url = "posts/cloud-native-python"
    weight = 3

[[languages.en.menu.main]]
    parent = "Books"
    name = "Cloud Native Java"
    url = "posts/cloud-native-java"
    weight = 4

[[languages.en.menu.main]]
    name = "About"
    url = "about"
    weight = 5
