######################## default configuration ####################
baseURL = "https://jimmysong.io"
title = "Jimmy Song - Cloud Native | Open Source | Community"
# post pagination
paginate = "10"
# post excerpt
summaryLength = "6"
metaDataFormat = "yaml"
hasCJKLanguage = true
DefaultContentLanguage = "zh"
# disqus short name
#disqusShortname = "jimmysong" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [] # desable language from here

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"

#################### default parameters ################################
[params]
logo = "images/logo.png"
# Meta data
description = "Jimmy Song's Blog"
author = "Jimmy Song"
# contact info
address = "Beijing, China"
email = "jimmysong@jimmysong.io"
wechat = "jimmysongio"
wechatCode = "/images/jimmysong-wechat-qr-code.jpg"
twitterCode = "/images/jimmysong-wechat-qr-code.jpg"
# contact form action
contact_form_action = "https://formspree.io/mpzdzdbj" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "UA-93485976-1" # your id
# Baidu tongji
baidu_key = "11f7d254cfa4e0ca44b175c66d379ecc"
# top header
top_header = true

# Preloader
[params.preloader]
enable = false
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.

# Subscription
[params.subscription]
enable = true
# mailchimp subsciption
#mailchimp_form_action = "https://jimmysong.us20.list-manage.com/subscribe/post?u=cca519d8764547a389f52c57f&amp;id=e8e9e07dcc"
# Use RSS instead
mailchimp_form_action = "/blog/index.xml"
mailchimp_form_name = "b_cca519d8764547a389f52c57f_e8e9e07dcc"

# google map
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

############################# social site ########################
[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/jimmysongio"

[[params.social]]
title = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/rootsongjc"

[[params.social]]
title = "linkedin"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "https://linkedin.com/in/jimmysongio"


################################### English language #####################################
[Languages.en]
languageName = "English"
languageCode = "en-us"
contentDir = "content/en"
weight = 1
home = "Home"
# copyright
copyright = "Copyright &copy; 2020 Jimmy Song All Right Reserved; Powerd by Hugo with [educenter](https://github.com/themefisher/educenter-hugo) theme"

# main menu
[[menu.main]]
name = "About"
URL = "about"
weight = 1

[[menu.main]]
name = "Book"
URL = "book"
weight = 2

[[menu.main]]
weight = 3
name = "More"
hasChildren = true

  [[menu.main]]
  parent = "More"
  name = "Partner"
  URL = "partner"

  [[menu.main]]
  parent = "More"
  name = "Notice"
  URL = "notice"

  [[menu.main]]
  parent = "More"
  name = "Event"
  URL = "event"

[[menu.main]]
name = "Blog"
URL = "blog"
weight = 4

[[menu.main]]
name = "Contact"
URL = "contact"
weight = 5


# footer menu

[[menu.footer]]
name = "Partner"
URL = "/partner"

[[menu.footer]]
name = "Event"
URL = "/event"

[[menu.footer]]
name = "Notice"
URL = "/notice"

[[menu.footer]]
name = "Awesome Cloud Native"
URL = "/awesome-cloud-native"

################################### Chinese language #####################################
[Languages.zh]
languageName = "中文"
languageCode = "zh"
contentDir = "content/zh"
weight = 2
home = "主页"
# copyright
copyright = "Copyright &copy; 2020 Jimmy Song 保留所有权利；基于 Hugo [educenter](https://github.com/themefisher/educenter-hugo)  主题构建"

# main menu
[[Languages.zh.menu.main]]
name = "关于"
URL = "about"
weight = 1

[[Languages.zh.menu.main]]
name = "图书"
URL = "book"
weight = 2

[[Languages.zh.menu.main]]
weight = 3
name = "更多"
hasChildren = true

  [[Languages.zh.menu.main]]
  parent = "更多"
  name = "伙伴"
  URL = "partner"

  [[Languages.zh.menu.main]]
  parent = "更多"
  name = "通知"
  URL = "notice"

  [[Languages.zh.menu.main]]
  parent = "更多"
  name = "活动"
  URL = "event"

[[Languages.zh.menu.main]]
name = "博客"
URL = "blog"
weight = 4

[[Languages.zh.menu.main]]
name = "招聘"
URL = "job"
weight = 5

[[Languages.zh.menu.main]]
name = "联系"
URL = "contact"
weight = 6

# footer menu

[[Languages.zh.menu.footer]]
name = "伙伴"
URL = "partner"

[[Languages.zh.menu.footer]]
name = "通知"
URL = "notice"

[[Languages.zh.menu.footer]]
name = "活动"
URL = "event"

[[Languages.zh.menu.footer]]
name = "Awesome Cloud Native"
URL = "/awesome-cloud-native"
