baseurl = "https://jimmysong.io/"
DefaultContentLanguage = "en"
hasCJKLanguage = true
languageCode = "zh"
title = "Jimmy Song"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = false
pygmentCodeFences = true
googleAnalytics = "UA-93485976-1"

[Params]
hello = "Hi,I'm Jimmy"
subtitle = "A CNCF Ambassador and Developer Advocate on Cloud Native"
logo = "https://res.cloudinary.com/jimmysong/raw/upload/rootsongjc-hugo/avatar-icon.png"
favicon = "https://res.cloudinary.com/jimmysong/raw/upload/rootsongjc-hugo/favicon.ico"
share_img = "https://ws4.sinaimg.cn/large/006tKfTcly1ft1oje0atgj31kw1kzk1j.jpg"
dateFormat = "January 2, 2006"
commit = false
rss = true
# ad section, comment this to disable it
ad = true
# GoogleAdsense
adsense = true
# reward button, comment this to disable it
reward = true
# baguettebox gallery, comment this to disable it
baguettebox = true
baiduKey = "11f7d254cfa4e0ca44b175c66d379ecc"
#comments = false
#sharebutton = true
algolia = "d2134c5a8d250e6d3246594240c45201" # API key
#gcse = "012737790962522169780:fd1izxsfgrs" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
description = "宋净超的博客|Cloud Native|云原生布道师"
errorpage = "https://res.cloudinary.com/jimmysong/image/upload/images/404-not-found-cat.png"

[[Params.bigimg]]
src = "https://ws1.sinaimg.cn/large/006tNc79ly1fyzhvztw7ij31i40u0u10.jpg"
desc = "Service Mesh Meetup #5 Guangzhou - Jan 6, 2019"

[[Params.bigimg]]
src = "https://ws1.sinaimg.cn/large/006tNbRwly1fxpvv5xakij32470u0npf.jpg"
desc = "Service Mesh Meetup #4 Shanghai - Nov 25, 2018"

[[Params.bigimg]]
src = "https://ws2.sinaimg.cn/large/006tNbRwly1fx80odnismj31jk0lm7wh.jpg"
desc = "ServiceMesher community members at KubeCon Shanghai - Nov 13, 2018"

[[Params.bigimg]]
src = "https://ws4.sinaimg.cn/large/006tNbRwly1fx80jwyftkj31jk0w5x6p.jpg"
desc = "Envoy,Istio and ServiceMesher community members at KubeCon Shanghai - Nov 14, 2018"

[[Params.bigimg]]
src = "https://ws2.sinaimg.cn/large/006tNbRwly1fwvuai4i9nj31860mce81.jpg"
desc = "Josh Long&Me with his book translated by me at SpringTour Beijing - Nov 3, 2018"

[[Params.bigimg]]
src = "https://ws4.sinaimg.cn/large/006tNbRwgy1fvlxgaxyj0j30xc0g7n4u.jpg"
desc = "At CNCF booth, the Computing Conference in Hangzhou - Sept 21, 2018"

[[Params.bigimg]]
src = "https://ws2.sinaimg.cn/large/0069RVTdly1fuoclagh35j318g0iz1kx.jpg"
desc = "Service Mesh Meetup #3 Shenzhen - Aug 25, 2018"

[[Params.bigimg]]
src = "https://ws3.sinaimg.cn/large/0069RVTdly1fu5luiuruvj31kw0kukjw.jpg"
desc = "Service Mesh Meetup #2 Beijing - Jul 29, 2018"

[[Params.bigimg]]
src = "https://ws2.sinaimg.cn/large/006tKfTcly1ft1mp16tllj31b00loe82.jpg"
desc = "Service Mesh Meetup #1 Hangzhou - Jun 30, 2018"

[[Params.bigimg]]
src = "https://ws1.sinaimg.cn/large/00704eQkly1fs1gsumgt0j31kq0j4qv5.jpg"
desc = "Kubernetes Meetup Beijing - Aug 28, 2017"

[[Params.bigimg]]
src = "https://ws1.sinaimg.cn/large/00704eQkly1fs1gwrkdp4j33070xgnpe.jpg"
desc = "Istio Meetup in Beijing GDG - Apr 24, 2018"

[Author]
  name = "Jimmy Song(宋净超)"
  website = "https://jimmysong.io/about"
  #email = "jimmysong@jimmysong.io"
  facebook = "jimmysongio"
  #googleplus = "+jimmysong" # or xxxxxxxxxxxxxxxxxxxxx
  github = "rootsongjc"
  twitter = "jimmysongio"
  linkedin = "jimmysongio"
  #500px = "jimmysongio"
  #medium = "jimmysongio"
  #instagram = "jimmysongio"
  weibo = "jimmysongio"

[[menu.main]]
    identifier = "Categories"
    name = "Categories"
    weight = 1

[[menu.main]]
    parent = "Categories"
    name = "kubernetes"
    url = "categories/kubernetes"
    weight = 1

[[menu.main]]
    parent = "Categories"
    name = "Istio"
    url = "categories/istio"
    weight = 2

[[menu.main]]
    parent = "Categories"
    name = "Cloud Native"
    url = "categories/cloud-native"
    weight = 3

[[menu.main]]
    parent = "Categories"
    name = "Microservices"
    url = "categories/microservices"
    weight = 4

[[menu.main]]
    parent = "Categories"
    name = "Service Mesh"
    url = "categories/service-mesh"
    weight = 5

[[menu.main]]
    parent = "Categories"
    name = "Devops"
    url = "categories/devops"
    weight = 6

[[menu.main]]
    parent = "Categories"
    name = "Serverless"
    url = "categories/serverless"
    weight = 7

[[menu.main]]
    parent = "Categories"
    name = "Tags"
    url = "tags"
    weight = 8

[[menu.main]]
    identifier = "Gitbooks"
    name = "Gitbooks"
    weight = 2

[[menu.main]]
    parent = "Gitbooks"
    name = "Istio handbook"
    url = "istio-handbook"
    weight = 1

[[menu.main]]
    parent = "Gitbooks"
    name = "Kubernetes handbook"
    url = "kubernetes-handbook"
    weight = 2

[[menu.main]]
    parent = "Gitbooks"
    name = "Docker handbook"
    url = "docker-handbook"
    weight = 3

[[menu.main]]
    parent = "Gitbooks"
    name = "Hugo Handbook"
    url = "hugo-handbook"
    weight = 4

[[menu.main]]
    parent = "Gitbooks"
    name = "Migrating to Cloud Native"
    url = "migrating-to-cloud-native-application-architectures"
    weight = 5

[[menu.main]]
    identifier = "Books"
    name = "Books"
    weight = 3

[[menu.main]]
    parent = "Books"
    name = "未来架构 - 从服务化到云原生"
    url = "posts/future-architecture-from-soa-to-cloud-native"
    weight = 1

[[menu.main]]
    parent = "Books"
    name = "Cloud Native Go"
    url = "posts/cloud-native-go"
    weight = 2

[[menu.main]]
    parent = "Books"
    name = "Cloud Native Python"
    url = "posts/cloud-native-python"
    weight = 3

[[menu.main]]
    parent = "Books"
    name = "Cloud Native Java"
    url = "posts/cloud-native-java"
    weight = 4

[[menu.main]]
    name = "Careers"
    url = "jobs"
    weight = 4

[[menu.main]]
    name = "About"
    url = "about"
    weight = 5
